[[main]]
  name = "博客"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "项目"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10
