colorScheme = "custom"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = false
  showBreadcrumbs = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showRelatedContent = true
  relatedContentLimit = 3

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true
  showBreadcrumbs = true

[term]
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = true
  cardView = true
